numeric_vector <- c(1,2,3,4,5)  
character_vector<-c("apple", "orang", "banana") 
sum_result<-sum(numeric_vector) 
multiplied_vector<-numeric_vector * 2 
print(multiplied_vector)
thismatrix <- matrix (c (1,2,3,4,5,6), nrow = 3, ncol = 2)  
print(thismatrix)
empName = c("Debi", "Sandeep", "Subham", "Shiba") 
print(empName) 
music_genre <-factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz")) 
levels(music_genre)